import './globals.css'
import { Providers } from './providers'
import {
  DynamicContextProvider,
  DynamicWidget,
  getAuthToken
} from '@dynamic-labs/sdk-react-core'
import { StarknetWalletConnectors } from '@dynamic-labs/starknet'

export const metadata = {
  title: 'AI Web3 Bot - Makes life easier 🛸',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">

      <body>
      <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DynamicWidget />
        {children}
      </Providers>
      </body>
      
    </html>
  )
}
